version: "3"

services:
    postgres_db:
        image: postgres
        volumes: 
            - postgres_vol:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=lol_winrate
        networks:
            - inner_net

    lol_winrate_django:
        build: ./
        image: lol_winrate_django
        depends_on:
            - postgres_db
        networks:
            - inner_net
            - gateway
        ports:
            - 80:80

    memcached:
        image: memcached
        networks: 
            - inner_net

networks:
    inner_net:
    gateway:

volumes:
    postgres_vol: