# Generated by Django 3.1.4 on 2021-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champ_winrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('win_rate', models.FloatField()),
                ('source', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key_db', models.CharField(default='0', max_length=32)),
                ('score', models.IntegerField()),
                ('source', models.IntegerField()),
                ('champ1', models.IntegerField()),
                ('champ2', models.IntegerField()),
                ('is_finished', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
